### ISSUE TITLE
Parser returning ts-error

### ISSUE THREAD

**Issue by dextersiah** [react-component/input-number#552]
I'm using the example parser and formatter in the example demo [here](https://input-number.vercel.app/example#formatter)

But I kept getting an error regarding the parser

```
Type '(value: string | undefined) => string' is not assignable to type '(displayValue: string | undefined) => number'.
  Type 'string' is not assignable to type 'number'.ts(2322)
InputNumber.d.ts(20, 5): The expected type comes from property 'parser' which is declared here on type 'IntrinsicAttributes & InputNumberProps<number> & { children?: ReactNode; } & { ref?: Ref<HTMLInputElement> | undefined; }'
```

I can remove the error by setting the value type to any but if I try to type on the input I get this error on the console.

```
Warning: Something warning of cursor restore. Please fire issue about this: An attempt was made to use an object that is not, or is no longer, usable 
InputNumber<@webpack-internal:///./node_modules/rc-input-number/es/InputNumber.js:59:26
```

Simple Replicate 
https://codesandbox.io/s/broken-lake-28h1gi?file=/src/App.tsx

**Comment by ovpv** [comment]
Hi there, Based on the type definitions, parser prop function expects a return type of number.  There are 2 issues i see in your code:

1.  the return value inside if condition is of type string instead of a number.
2.  there is no default return type after if statement hence it returns undefined by default.

Here is the expected parser prop function as per you example:

```
    parser={(value) => {
        if (value) {
          console.log(typeof value)
          return Number(value.replace(/\$\s?|(,*)/g, ""));
        }
        return Number(value);
   }}
```

Hope this helps
